version: "3"
services:
  jenkins-master:
    image: docker.io/jenkins/jenkins:2.377-jdk17
    container_name: jenkins
    hostname: jenkins
    restart: always
    privileged: true
    network_mode: 'host'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/var/jenkins_home
    environment:
      - JAVA_OPTS='-Djava.util.logging.config.file=/var/jenkins_home/log.properties
      - TZ=Asia/Shanghai
