version: "3"
services:
  db:
    image: mysql:8.0.19
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Shanghai
    command: --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/mysql/:/data/mysql
      - ./conf/my.cnf:/etc/my.cnf
    cap_add:
      - SYS_NICE
    networks:
      - custom_network

networks:
  custom_network:
    external:
      name: network_mysql
