### nginx基础镜像 Dockerfile 文件内容
# 基础镜像
FROM centos:7
# 作者
LABEL MAINTAINER zhanghaijun
#执行下面命令，安装基础环境
RUN yum install -y gcc gcc-c++ make \
  openssl-devel pcre-devel gd-devel \
  iproute net-tools telnet wget curl && \
  yum clean all && \
  rm -rf /var/cache/yum/*
#nginx到容器里 并编译安装
RUN wget http://nginx.org/download/nginx-1.23.1.tar.gz && \
  tar zxf nginx-1.23.1.tar.gz && \
  cd nginx-1.23.1 && \
  ./configure --prefix=/usr/local/nginx \
  --with-http_ssl_module \
  --with-http_stub_status_module && \
  make -j 4 && make install && \
  rm -rf /usr/local/nginx/html/* && \
  echo "ok" >> /usr/local/nginx/html/index.html && \
  cd / && rm -rf nginx-2* && \
  #做软连接
  ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
#设置环境变量
ENV PATH $PATH:/usr/local/nginx/sbin
#拷贝
#COPY nginx.conf /usr/local/nginx/conf/nginx.conf
#指定工作目录
WORKDIR /usr/local/nginx
#暴露端口
EXPOSE 80
#运行这个镜像，默认执行的命令
CMD ["nginx", "-g", "daemon off;"]
