#!/bin/bash
if [ "$CLOUDSERVER_DEBUG" == "DEBUG" ];then
  set -x
fi

log(){
  local level=$1
  shift
  local prefix=$1
  shift
  local msg=$@
  local timestamp=$(date '+%Y-%m-%d %H:%M:%''S')
  echo "[$timestamp][$level][$prefix]" $msg
  local log_file=/var/log/cloudserver-${prefix}.log
  echo "[$timestamp][$level][$prefix]" $msg >> $log_file
}

info(){
  log "INFO" "POSTINSTALL" $@
}
warn(){
  log "WARN" "POSTINSTALL" $@
}
error(){
  log "ERROR" "POSTINSTALL" $@
  exit 100
}

install_init(){
  local common_install_file=/opt/cloudserver/installer/commonInstall
  if [ -f $common_install_file ];then
    . $common_install_file
  else
    echo "功能库文件[$common_install_file]不存在"
    exit 100
  fi
}

install_check_process(){
  info "停止产品相关进程"
}

install_command(){
  info "安装工具快捷方式"
  ln -sf /opt/cloudserver/bin/cloudserver-startapp /usr/bin/cloudserver-startapp
  ln -sf /opt/cloudserver/bin/cloudserver-stopapp /usr/bin/cloudserver-stopapp
}

install_main(){
  install_runtime
  install_check_process
  install_service
  install_command
  info "安装正常结束，请重新启动操作系统"
}

main()
{
  # RPM安装
	case $1 in
		1 )
			shift
      install_init
      install_main $@
      exit 0
			;;
		2 )
			shift
      install_init
      install_main $@
      exit 0
			;;
	esac

  # DEB安装
	case $1 in
		configure )
			shift
      install_init
      install_main $@
			;;
	esac
}

info "-----------------------------------------------------------------------------------"
info "安装参数:$@"
main $@
exit 0
