name: CI

# 在master分支发生push事件时触发。
on:
  push:
    branches:
      - master

env: # 设置环境变量
  TZ: Asia/Shanghai # 时区（设置时区可使页面中的`最近更新时间`使用时区时间）

jobs: # 工作流
  build: # 自定义名称
    runs-on: ubuntu-latest #运行在虚拟机环境ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkou
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"
          cache: pnpm
      - name: run deploy.sh
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          CODING_TOKEN: ${{ secrets.CODING_TOKEN }}
        run: npm install --registry=https://registry.npm.taobao.org && npm run deploy

#      - name: Build and Deploy # 步骤3 （只提交到github可以使用这个步骤）
#        uses: zhanghaijun666/zhanghaijun666.github.io.git@master # 作用：将项目构建和部署到github。 https://github.com/JamesIves/github-pages-deploy-action
#        env: # 设置环境变量
#          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # toKen私密变量
#          BASE_BRANCH: master # 要部署的文件夹所在的分支.
#          BRANCH: master # 部署到的分支
#          FOLDER: docs/.vuepress/dist # 要部署的文件夹.
#          BUILD_SCRIPT: npm install && npm run build && cd docs/.vuepress/dist && echo 'haijunit.top' > CNAME && cd - # 部署前要执行的命令（记得cd进入某个目录后，后面要cd -退回开始的目录）
